use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use rusqlite::{Connection, OptionalExtension};

use crate::db;
use crate::models::MarkdownSyncResult;
use crate::{MemhubError, Result};

const AGENTS_FILENAME: &str = "AGENTS.md";
const CLAUDE_FILENAME: &str = "CLAUDE.md";
const RENDERED_SUBDIR: &str = "rendered";

pub fn sync_project(start: &Path) -> Result<MarkdownSyncResult> {
    let ctx = db::open_project(start)?;
    let body = render_managed_body(&ctx.conn)?;
    let output_dir = ctx.paths.memhub_dir.join(RENDERED_SUBDIR);
    fs::create_dir_all(&output_dir)?;
    let backup_dir = ctx.paths.memhub_dir.join("backups").join("markdown");

    let mut updated_files = Vec::new();
    let mut backup_files = Vec::new();

    for filename in [AGENTS_FILENAME, CLAUDE_FILENAME] {
        let path = output_dir.join(filename);
        let existing = if path.exists() {
            fs::read_to_string(&path)?
        } else {
            String::new()
        };

        if existing == body {
            continue;
        }

        let backup_path = if path.exists() {
            Some(create_backup(&path, &backup_dir)?)
        } else {
            None
        };

        write_with_replace(&path, &body)?;
        updated_files.push(path);
        if let Some(bp) = backup_path {
            backup_files.push(bp);
        }
    }

    if !updated_files.is_empty() {
        db::log_write(
            &ctx.conn,
            "cli:user",
            "markdown_sync",
            None,
            "update",
            "sync-md",
        )?;
    }

    Ok(MarkdownSyncResult {
        updated_files,
        backup_files,
    })
}

pub fn sync_if_enabled(start: &Path) -> Result<()> {
    let ctx = db::open_project(start)?;
    if ctx.config.auto_sync_md {
        let _ = sync_project(start)?;
    }

    Ok(())
}

fn render_managed_body(conn: &Connection) -> Result<String> {
    let build = load_command_summary(conn, "build")?;
    let test = load_command_summary(conn, "test")?;
    let (open_tasks, blocked_tasks) = load_task_counts(conn)?;
    let decisions = load_active_decisions(conn)?;
    let quirks = load_known_quirks(conn)?;

    let mut lines = vec![
        "# Project state (machine-local, generated by memhub)".to_string(),
        String::new(),
        "This file is regenerated from the local memhub DB on every sync.".to_string(),
        "It is never committed to git. Each machine maintains its own copy.".to_string(),
        String::new(),
        format!("**Build:** {}", format_command_summary(build.as_ref())),
        format!("**Test:** {}", format_command_summary(test.as_ref())),
        format!(
            "**Active tasks:** {} open, {} blocked - see `memhub task list --status open`",
            open_tasks, blocked_tasks
        ),
        String::new(),
        "## Durable decisions".to_string(),
    ];

    if decisions.is_empty() {
        lines.push("- None recorded.".to_string());
    } else {
        for (title, decided_at) in decisions {
            lines.push(format!("- {} ({})", title, decided_at));
        }
    }

    lines.push(String::new());
    lines.push("## Known quirks".to_string());
    if quirks.is_empty() {
        lines.push("- None recorded.".to_string());
    } else {
        for quirk in quirks {
            lines.push(format!("- {}", quirk));
        }
    }

    lines.push(String::new());

    Ok(lines.join("\n"))
}

pub(crate) fn create_backup(path: &Path, backup_dir: &Path) -> Result<PathBuf> {
    fs::create_dir_all(backup_dir)?;

    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| {
            MemhubError::InvalidInput(format!("invalid markdown filename: {}", path.display()))
        })?;
    let stamp = backup_stamp()?;

    for attempt in 0..1000 {
        let suffix = if attempt == 0 {
            String::new()
        } else {
            format!("-{attempt}")
        };
        let backup_path = backup_dir.join(format!("{stamp}{suffix}-{file_name}.bak"));
        if !backup_path.exists() {
            let _ = fs::copy(path, &backup_path)?;
            return Ok(backup_path);
        }
    }

    Err(MemhubError::InvalidInput(format!(
        "failed to allocate a backup path for {}",
        path.display()
    )))
}

pub(crate) fn backup_stamp() -> Result<String> {
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|err| {
            MemhubError::InvalidInput(format!("system clock is before unix epoch: {err}"))
        })?;
    Ok(format!("{}-{:09}", now.as_secs(), now.subsec_nanos()))
}

pub(crate) fn write_with_replace(path: &Path, updated_content: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }

    let temp_path = temp_path_for(path)?;
    fs::write(&temp_path, updated_content)?;

    // `fs::rename` atomically replaces an existing regular file on both Unix
    // (rename(2)) and Windows (MoveFileExW + MOVEFILE_REPLACE_EXISTING). No
    // pre-remove step is needed, and removing creates a window where the
    // destination temporarily does not exist.
    if let Err(err) = fs::rename(&temp_path, path) {
        let _ = fs::remove_file(&temp_path);
        return Err(err.into());
    }

    Ok(())
}

pub(crate) fn temp_path_for(path: &Path) -> Result<PathBuf> {
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| {
            MemhubError::InvalidInput(format!("invalid markdown filename: {}", path.display()))
        })?;
    let stamp = backup_stamp()?;
    Ok(path.with_file_name(format!(".{file_name}.{stamp}.tmp")))
}

fn load_command_summary(conn: &Connection, kind: &str) -> Result<Option<(String, String)>> {
    conn.query_row(
        "SELECT cmdline, last_run_at
         FROM commands
         WHERE project_id = 1
           AND kind = ?1
           AND last_exit_code = 0
           AND last_run_at IS NOT NULL
         ORDER BY last_run_at DESC
         LIMIT 1",
        [kind],
        |row| Ok((row.get(0)?, row.get(1)?)),
    )
    .optional()
    .map_err(Into::into)
}

fn format_command_summary(summary: Option<&(String, String)>) -> String {
    match summary {
        Some((cmdline, last_run_at)) => {
            format!("`{}` (last verified: {})", cmdline, last_run_at)
        }
        None => "`n/a`".to_string(),
    }
}

fn load_task_counts(conn: &Connection) -> Result<(i64, i64)> {
    let open: i64 = conn.query_row(
        "SELECT COUNT(*)
         FROM tasks
         WHERE project_id = 1 AND status = 'open'",
        [],
        |row| row.get(0),
    )?;
    let blocked: i64 = conn.query_row(
        "SELECT COUNT(*)
         FROM tasks
         WHERE project_id = 1 AND status = 'blocked'",
        [],
        |row| row.get(0),
    )?;

    Ok((open, blocked))
}

fn load_active_decisions(conn: &Connection) -> Result<Vec<(String, String)>> {
    let mut stmt = conn.prepare(
        "SELECT title, decided_at
         FROM decisions
         WHERE project_id = 1 AND status = 'active'
         ORDER BY decided_at DESC, id DESC
         LIMIT 5",
    )?;

    let rows = stmt.query_map([], |row| Ok((row.get(0)?, row.get(1)?)))?;
    rows.collect::<std::result::Result<Vec<_>, _>>()
        .map_err(Into::into)
}

fn load_known_quirks(conn: &Connection) -> Result<Vec<String>> {
    let mut stmt = conn.prepare(
        "SELECT key, value
         FROM facts
         WHERE project_id = 1
           AND (
             key LIKE 'quirk.%'
             OR key LIKE 'quirk:%'
             OR key = 'quirk'
             OR key LIKE 'known-quirk%'
             OR key LIKE 'known_quirk%'
           )
         ORDER BY key ASC",
    )?;

    let rows = stmt.query_map([], |row| {
        let key: String = row.get(0)?;
        let value: String = row.get(1)?;
        Ok(match key.as_str() {
            "quirk" => value,
            _ => format!("{key}: {value}"),
        })
    })?;

    rows.collect::<std::result::Result<Vec<_>, _>>()
        .map_err(Into::into)
}
