use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use rusqlite::{Connection, OptionalExtension};

use crate::db;
use crate::models::MarkdownSyncResult;
use crate::{MemhubError, Result};

const AGENTS_FILENAME: &str = "AGENTS.md";
const CLAUDE_FILENAME: &str = "CLAUDE.md";
const MANAGED_START: &str = "<!-- memhub:managed:start -->";
const MANAGED_END: &str = "<!-- memhub:managed:end -->";

pub fn sync_project(start: &Path) -> Result<MarkdownSyncResult> {
    let ctx = db::open_project(start)?;
    let rendered = render_managed_block(&ctx.conn)?;
    let backup_dir = ctx.paths.memhub_dir.join("backups").join("markdown");

    let mut plans = Vec::new();
    for filename in [AGENTS_FILENAME, CLAUDE_FILENAME] {
        let path = ctx.paths.repo_root.join(filename);
        plans.push(plan_sync(&path, &rendered)?);
    }

    let mut updated_files = Vec::new();
    let mut backup_files = Vec::new();
    for plan in plans {
        if let Some(outcome) = apply_sync_plan(plan, &backup_dir)? {
            updated_files.push(outcome.path);
            if let Some(backup_path) = outcome.backup_path {
                backup_files.push(backup_path);
            }
        }
    }

    if !updated_files.is_empty() {
        db::log_write(
            &ctx.conn,
            "cli:user",
            "markdown_sync",
            None,
            "update",
            "sync-md",
        )?;
    }

    Ok(MarkdownSyncResult {
        updated_files,
        backup_files,
    })
}

pub fn sync_if_enabled(start: &Path) -> Result<()> {
    let ctx = db::open_project(start)?;
    if ctx.config.auto_sync_md {
        let _ = sync_project(start)?;
    }

    Ok(())
}

fn render_managed_block(conn: &Connection) -> Result<String> {
    let build = load_command_summary(conn, "build")?;
    let test = load_command_summary(conn, "test")?;
    let (open_tasks, blocked_tasks) = load_task_counts(conn)?;
    let decisions = load_active_decisions(conn)?;
    let quirks = load_known_quirks(conn)?;

    let mut lines = vec![
        MANAGED_START.to_string(),
        "<!-- DO NOT EDIT BELOW THIS LINE. Generated by memhub. -->".to_string(),
        "<!-- To change, use `memhub fact add` / `memhub decision add` or edit the DB. -->"
            .to_string(),
        String::new(),
        "## Project state (auto-generated)".to_string(),
        String::new(),
        format!("**Build:** {}", format_command_summary(build.as_ref())),
        format!("**Test:** {}", format_command_summary(test.as_ref())),
        format!(
            "**Active tasks:** {} open, {} blocked - see `memhub task list --status open`",
            open_tasks, blocked_tasks
        ),
        String::new(),
        "### Durable decisions".to_string(),
    ];

    if decisions.is_empty() {
        lines.push("- None recorded.".to_string());
    } else {
        for (title, decided_at) in decisions {
            lines.push(format!("- {} ({})", title, decided_at));
        }
    }

    lines.push(String::new());
    lines.push("### Known quirks".to_string());
    if quirks.is_empty() {
        lines.push("- None recorded.".to_string());
    } else {
        for quirk in quirks {
            lines.push(format!("- {}", quirk));
        }
    }

    lines.push(String::new());
    lines.push(MANAGED_END.to_string());

    Ok(lines.join("\n"))
}

#[derive(Debug)]
struct SyncPlan {
    path: PathBuf,
    updated_content: Option<String>,
    create_backup: bool,
}

#[derive(Debug)]
struct SyncOutcome {
    path: PathBuf,
    backup_path: Option<PathBuf>,
}

fn plan_sync(path: &Path, rendered_block: &str) -> Result<SyncPlan> {
    let existing = if path.exists() {
        fs::read_to_string(path)?
    } else {
        String::new()
    };

    let updated = match inspect_managed_block(path, &existing)? {
        ManagedBlockState::Present { start, end } => {
            let mut next = String::new();
            next.push_str(&existing[..start]);
            next.push_str(rendered_block);
            next.push_str(&existing[end..]);
            next
        }
        ManagedBlockState::Missing if existing.trim().is_empty() => format!("{rendered_block}\n"),
        ManagedBlockState::Missing => {
            let trimmed = existing.trim_end_matches(['\r', '\n']);
            format!("{trimmed}\n\n{rendered_block}\n")
        }
    };

    if updated == existing {
        return Ok(SyncPlan {
            path: path.to_path_buf(),
            updated_content: None,
            create_backup: false,
        });
    }

    Ok(SyncPlan {
        path: path.to_path_buf(),
        updated_content: Some(updated),
        create_backup: path.exists(),
    })
}

fn apply_sync_plan(plan: SyncPlan, backup_dir: &Path) -> Result<Option<SyncOutcome>> {
    let Some(updated_content) = plan.updated_content else {
        return Ok(None);
    };

    let backup_path = if plan.create_backup {
        Some(create_backup(&plan.path, backup_dir)?)
    } else {
        None
    };

    write_with_replace(&plan.path, &updated_content)?;

    Ok(Some(SyncOutcome {
        path: plan.path,
        backup_path,
    }))
}

enum ManagedBlockState {
    Missing,
    Present { start: usize, end: usize },
}

fn inspect_managed_block(path: &Path, content: &str) -> Result<ManagedBlockState> {
    let starts = collect_marker_positions(content, MANAGED_START);
    let ends = collect_marker_positions(content, MANAGED_END);

    if starts.is_empty() && ends.is_empty() {
        return Ok(ManagedBlockState::Missing);
    }

    if starts.len() != 1 || ends.len() != 1 {
        return Err(invalid_managed_markdown(
            path,
            "expected exactly one managed block start marker and one managed block end marker",
        ));
    }

    let start = starts[0];
    let end = ends[0];
    if end < start {
        return Err(invalid_managed_markdown(
            path,
            "managed block end marker appears before the start marker",
        ));
    }

    Ok(ManagedBlockState::Present {
        start,
        end: end + MANAGED_END.len(),
    })
}

fn collect_marker_positions(content: &str, marker: &str) -> Vec<usize> {
    content
        .match_indices(marker)
        .map(|(index, _)| index)
        .collect()
}

fn invalid_managed_markdown(path: &Path, reason: &str) -> MemhubError {
    MemhubError::InvalidManagedMarkdown {
        path: path.display().to_string(),
        reason: reason.to_string(),
    }
}

fn create_backup(path: &Path, backup_dir: &Path) -> Result<PathBuf> {
    fs::create_dir_all(backup_dir)?;

    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| {
            MemhubError::InvalidInput(format!("invalid markdown filename: {}", path.display()))
        })?;
    let stamp = backup_stamp()?;

    for attempt in 0..1000 {
        let suffix = if attempt == 0 {
            String::new()
        } else {
            format!("-{attempt}")
        };
        let backup_path = backup_dir.join(format!("{stamp}{suffix}-{file_name}.bak"));
        if !backup_path.exists() {
            let _ = fs::copy(path, &backup_path)?;
            return Ok(backup_path);
        }
    }

    Err(MemhubError::InvalidInput(format!(
        "failed to allocate a backup path for {}",
        path.display()
    )))
}

fn backup_stamp() -> Result<String> {
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|err| {
            MemhubError::InvalidInput(format!("system clock is before unix epoch: {err}"))
        })?;
    Ok(format!("{}-{:09}", now.as_secs(), now.subsec_nanos()))
}

fn write_with_replace(path: &Path, updated_content: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }

    let temp_path = temp_path_for(path)?;
    fs::write(&temp_path, updated_content)?;

    if path.exists() {
        fs::remove_file(path)?;
    }

    if let Err(err) = fs::rename(&temp_path, path) {
        let _ = fs::remove_file(&temp_path);
        return Err(err.into());
    }

    Ok(())
}

fn temp_path_for(path: &Path) -> Result<PathBuf> {
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| {
            MemhubError::InvalidInput(format!("invalid markdown filename: {}", path.display()))
        })?;
    let stamp = backup_stamp()?;
    Ok(path.with_file_name(format!(".{file_name}.{stamp}.tmp")))
}

fn load_command_summary(conn: &Connection, kind: &str) -> Result<Option<(String, String)>> {
    conn.query_row(
        "SELECT cmdline, last_run_at
         FROM commands
         WHERE project_id = 1
           AND kind = ?1
           AND last_exit_code = 0
           AND last_run_at IS NOT NULL
         ORDER BY last_run_at DESC
         LIMIT 1",
        [kind],
        |row| Ok((row.get(0)?, row.get(1)?)),
    )
    .optional()
    .map_err(Into::into)
}

fn format_command_summary(summary: Option<&(String, String)>) -> String {
    match summary {
        Some((cmdline, last_run_at)) => {
            format!("`{}` (last verified: {})", cmdline, last_run_at)
        }
        None => "`n/a`".to_string(),
    }
}

fn load_task_counts(conn: &Connection) -> Result<(i64, i64)> {
    let open: i64 = conn.query_row(
        "SELECT COUNT(*)
         FROM tasks
         WHERE project_id = 1 AND status = 'open'",
        [],
        |row| row.get(0),
    )?;
    let blocked: i64 = conn.query_row(
        "SELECT COUNT(*)
         FROM tasks
         WHERE project_id = 1 AND status = 'blocked'",
        [],
        |row| row.get(0),
    )?;

    Ok((open, blocked))
}

fn load_active_decisions(conn: &Connection) -> Result<Vec<(String, String)>> {
    let mut stmt = conn.prepare(
        "SELECT title, decided_at
         FROM decisions
         WHERE project_id = 1 AND status = 'active'
         ORDER BY decided_at DESC, id DESC
         LIMIT 5",
    )?;

    let rows = stmt.query_map([], |row| Ok((row.get(0)?, row.get(1)?)))?;
    rows.collect::<std::result::Result<Vec<_>, _>>()
        .map_err(Into::into)
}

fn load_known_quirks(conn: &Connection) -> Result<Vec<String>> {
    let mut stmt = conn.prepare(
        "SELECT key, value
         FROM facts
         WHERE project_id = 1
           AND (
             key LIKE 'quirk.%'
             OR key LIKE 'quirk:%'
             OR key = 'quirk'
             OR key LIKE 'known-quirk%'
             OR key LIKE 'known_quirk%'
           )
         ORDER BY key ASC",
    )?;

    let rows = stmt.query_map([], |row| {
        let key: String = row.get(0)?;
        let value: String = row.get(1)?;
        Ok(match key.as_str() {
            "quirk" => value,
            _ => format!("{key}: {value}"),
        })
    })?;

    rows.collect::<std::result::Result<Vec<_>, _>>()
        .map_err(Into::into)
}
