use std::fs;
use std::path::Path;

use rusqlite::{Connection, OptionalExtension};

use crate::Result;
use crate::db;
use crate::models::MarkdownSyncResult;

const AGENTS_FILENAME: &str = "AGENTS.md";
const CLAUDE_FILENAME: &str = "CLAUDE.md";
const MANAGED_START: &str = "<!-- memhub:managed:start -->";
const MANAGED_END: &str = "<!-- memhub:managed:end -->";

pub fn sync_project(start: &Path) -> Result<MarkdownSyncResult> {
    let ctx = db::open_project(start)?;
    let rendered = render_managed_block(&ctx.conn)?;

    let mut updated_files = Vec::new();
    for filename in [AGENTS_FILENAME, CLAUDE_FILENAME] {
        let path = ctx.paths.repo_root.join(filename);
        if sync_file(&path, &rendered)? {
            updated_files.push(path);
        }
    }

    if !updated_files.is_empty() {
        db::log_write(
            &ctx.conn,
            "cli:user",
            "markdown_sync",
            None,
            "update",
            "sync-md",
        )?;
    }

    Ok(MarkdownSyncResult { updated_files })
}

pub fn sync_if_enabled(start: &Path) -> Result<()> {
    let ctx = db::open_project(start)?;
    if ctx.config.auto_sync_md {
        let _ = sync_project(start)?;
    }

    Ok(())
}

fn render_managed_block(conn: &Connection) -> Result<String> {
    let build = load_command_summary(conn, "build")?;
    let test = load_command_summary(conn, "test")?;
    let (open_tasks, blocked_tasks) = load_task_counts(conn)?;
    let decisions = load_active_decisions(conn)?;
    let quirks = load_known_quirks(conn)?;

    let mut lines = vec![
        MANAGED_START.to_string(),
        "<!-- DO NOT EDIT BELOW THIS LINE. Generated by memhub. -->".to_string(),
        "<!-- To change, use `memhub fact add` / `memhub decision add` or edit the DB. -->"
            .to_string(),
        String::new(),
        "## Project state (auto-generated)".to_string(),
        String::new(),
        format!("**Build:** {}", format_command_summary(build.as_ref())),
        format!("**Test:** {}", format_command_summary(test.as_ref())),
        format!(
            "**Active tasks:** {} open, {} blocked - see `memhub task list --status open`",
            open_tasks, blocked_tasks
        ),
        String::new(),
        "### Durable decisions".to_string(),
    ];

    if decisions.is_empty() {
        lines.push("- None recorded.".to_string());
    } else {
        for (title, decided_at) in decisions {
            lines.push(format!("- {} ({})", title, decided_at));
        }
    }

    lines.push(String::new());
    lines.push("### Known quirks".to_string());
    if quirks.is_empty() {
        lines.push("- None recorded.".to_string());
    } else {
        for quirk in quirks {
            lines.push(format!("- {}", quirk));
        }
    }

    lines.push(String::new());
    lines.push(MANAGED_END.to_string());

    Ok(lines.join("\n"))
}

fn sync_file(path: &Path, rendered_block: &str) -> Result<bool> {
    let existing = if path.exists() {
        fs::read_to_string(path)?
    } else {
        String::new()
    };

    let updated = if let Some((start, end)) = find_managed_block(&existing) {
        let mut next = String::new();
        next.push_str(&existing[..start]);
        next.push_str(rendered_block);
        next.push_str(&existing[end..]);
        next
    } else if existing.trim().is_empty() {
        format!("{rendered_block}\n")
    } else {
        let trimmed = existing.trim_end_matches(['\r', '\n']);
        format!("{trimmed}\n\n{rendered_block}\n")
    };

    if updated == existing {
        return Ok(false);
    }

    fs::write(path, updated)?;
    Ok(true)
}

fn find_managed_block(content: &str) -> Option<(usize, usize)> {
    let start = content.find(MANAGED_START)?;
    let end = content[start..].find(MANAGED_END)? + start + MANAGED_END.len();
    Some((start, end))
}

fn load_command_summary(conn: &Connection, kind: &str) -> Result<Option<(String, String)>> {
    conn.query_row(
        "SELECT cmdline, last_run_at
         FROM commands
         WHERE project_id = 1
           AND kind = ?1
           AND last_exit_code = 0
           AND last_run_at IS NOT NULL
         ORDER BY last_run_at DESC
         LIMIT 1",
        [kind],
        |row| Ok((row.get(0)?, row.get(1)?)),
    )
    .optional()
    .map_err(Into::into)
}

fn format_command_summary(summary: Option<&(String, String)>) -> String {
    match summary {
        Some((cmdline, last_run_at)) => {
            format!("`{}` (last verified: {})", cmdline, last_run_at)
        }
        None => "`n/a`".to_string(),
    }
}

fn load_task_counts(conn: &Connection) -> Result<(i64, i64)> {
    let open: i64 = conn.query_row(
        "SELECT COUNT(*)
         FROM tasks
         WHERE project_id = 1 AND status = 'open'",
        [],
        |row| row.get(0),
    )?;
    let blocked: i64 = conn.query_row(
        "SELECT COUNT(*)
         FROM tasks
         WHERE project_id = 1 AND status = 'blocked'",
        [],
        |row| row.get(0),
    )?;

    Ok((open, blocked))
}

fn load_active_decisions(conn: &Connection) -> Result<Vec<(String, String)>> {
    let mut stmt = conn.prepare(
        "SELECT title, decided_at
         FROM decisions
         WHERE project_id = 1 AND status = 'active'
         ORDER BY decided_at DESC, id DESC
         LIMIT 5",
    )?;

    let rows = stmt.query_map([], |row| Ok((row.get(0)?, row.get(1)?)))?;
    rows.collect::<std::result::Result<Vec<_>, _>>()
        .map_err(Into::into)
}

fn load_known_quirks(conn: &Connection) -> Result<Vec<String>> {
    let mut stmt = conn.prepare(
        "SELECT key, value
         FROM facts
         WHERE project_id = 1
           AND (
             key LIKE 'quirk.%'
             OR key LIKE 'quirk:%'
             OR key = 'quirk'
             OR key LIKE 'known-quirk%'
             OR key LIKE 'known_quirk%'
           )
         ORDER BY key ASC",
    )?;

    let rows = stmt.query_map([], |row| {
        let key: String = row.get(0)?;
        let value: String = row.get(1)?;
        Ok(match key.as_str() {
            "quirk" => value,
            _ => format!("{key}: {value}"),
        })
    })?;

    rows.collect::<std::result::Result<Vec<_>, _>>()
        .map_err(Into::into)
}
